// Writes <package>/test/coverage_all_libs_test.dart, a test that imports
// every file under <package>/lib. `flutter test --coverage` only reports
// files some test loads, so without it an untested file would be missing from
// the report instead of counting as 0%. `make coverage` generates the file,
// runs the tests and deletes it again.
//
// Usage: dart run tool/gen_coverage_helper.dart <package-dir>
//        dart run tool/gen_coverage_helper.dart <package-dir> --remove
import 'dart:io';

/// Name of the generated test, relative to a package's `test/` directory.
const coverageHelperName = 'coverage_all_libs_test.dart';

/// Source of a test that imports each of [libFiles] (paths like
/// `lib/src/a.dart`, relative to the package) from package [name].
String renderCoverageHelper(String name, List<String> libFiles) {
  final sorted = [...libFiles]..sort();
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_coverage_helper.dart. Do not edit or')
    ..writeln('// commit; `make coverage` deletes it after the run.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln();
  for (var i = 0; i < sorted.length; i++) {
    final uri = sorted[i].substring('lib/'.length);
    buffer.writeln("import 'package:$name/$uri' as _i$i;");
  }
  buffer
    ..writeln()
    ..writeln('void main() {}');
  return buffer.toString();
}

void main(List<String> args) {
  if (args.isEmpty || args.length > 2) {
    stderr.writeln('usage: gen_coverage_helper.dart <package-dir> [--remove]');
    exit(64);
  }
  final dir = Directory(args[0]);
  final helper = File('${dir.path}/test/$coverageHelperName');
  if (args.length == 2 && args[1] == '--remove') {
    if (helper.existsSync()) helper.deleteSync();
    // Drop the test/ directory too when the helper was all it held.
    if (helper.parent.existsSync() && helper.parent.listSync().isEmpty) {
      helper.parent.deleteSync();
    }
    return;
  }
  final name = RegExp(
    r'^name:\s*(\S+)',
    multiLine: true,
  ).firstMatch(File('${dir.path}/pubspec.yaml').readAsStringSync())!.group(1)!;
  final libFiles = Directory('${dir.path}/lib')
      .listSync(recursive: true)
      .whereType<File>()
      .map((f) => f.path.replaceAll(r'\', '/'))
      .where((p) => p.endsWith('.dart'))
      .map((p) => p.substring(dir.path.length + 1))
      .toList();
  if (libFiles.isEmpty) {
    stderr.writeln('✗ ${dir.path}/lib has no Dart files to cover');
    exit(1);
  }
  helper.parent.createSync(recursive: true);
  helper.writeAsStringSync(renderCoverageHelper(name, libFiles));
}
