// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum NativeShellApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Where the native sidebar is.
enum NativeSidebar: Int, CaseIterable {
  case hidden = 0
  case overlay = 1
  case tiled = 2
}

/// Why the native shell is not installed.
enum NativeUnavailableReason: Int, CaseIterable {
  case notIPad = 0
  case osTooOld = 1
  case iPadAppOnMac = 2
  case notEnabled = 3
  case disabledByEnvironment = 4
  case rootNotFlutter = 5
  case registeredLate = 6
}

/// Test-only: what `debugTap` taps.
enum NativeTapTarget: Int, CaseIterable {
  case destination = 0
  case trailing = 1
  case footer = 2
}

/// What `attach()` returns and `onStateChanged` pushes.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeShellState: Hashable, CustomStringConvertible {
  var installed: Bool
  var compact: Bool
  var sidebar: NativeSidebar
  var unavailableReason: NativeUnavailableReason? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeShellState? {
    let installed = pigeonVar_list[0] as! Bool
    let compact = pigeonVar_list[1] as! Bool
    let sidebar = pigeonVar_list[2] as! NativeSidebar
    let unavailableReason: NativeUnavailableReason? = nilOrValue(pigeonVar_list[3])

    return NativeShellState(
      installed: installed,
      compact: compact,
      sidebar: sidebar,
      unavailableReason: unavailableReason
    )
  }
  func toList() -> [Any?] {
    return [
      installed,
      compact,
      sidebar,
      unavailableReason,
    ]
  }
  static func == (lhs: NativeShellState, rhs: NativeShellState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.installed, rhs.installed) && NativeShellApiPigeonInternal.deepEquals(lhs.compact, rhs.compact) && NativeShellApiPigeonInternal.deepEquals(lhs.sidebar, rhs.sidebar) && NativeShellApiPigeonInternal.deepEquals(lhs.unavailableReason, rhs.unavailableReason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeShellState")
    NativeShellApiPigeonInternal.deepHash(value: installed, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: compact, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sidebar, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: unavailableReason, hasher: &hasher)
  }

  public var description: String {
    return "NativeShellState(installed: \(String(describing: installed)), compact: \(String(describing: compact)), sidebar: \(String(describing: sidebar)), unavailableReason: \(String(describing: unavailableReason)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeTab: Hashable, CustomStringConvertible {
  var title: String
  var sfSymbol: String
  var badge: String? = nil
  var sidebarOnly: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTab? {
    let title = pigeonVar_list[0] as! String
    let sfSymbol = pigeonVar_list[1] as! String
    let badge: String? = nilOrValue(pigeonVar_list[2])
    let sidebarOnly = pigeonVar_list[3] as! Bool

    return NativeTab(
      title: title,
      sfSymbol: sfSymbol,
      badge: badge,
      sidebarOnly: sidebarOnly
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      sfSymbol,
      badge,
      sidebarOnly,
    ]
  }
  static func == (lhs: NativeTab, rhs: NativeTab) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol) && NativeShellApiPigeonInternal.deepEquals(lhs.badge, rhs.badge) && NativeShellApiPigeonInternal.deepEquals(lhs.sidebarOnly, rhs.sidebarOnly)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeTab")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: badge, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sidebarOnly, hasher: &hasher)
  }

  public var description: String {
    return "NativeTab(title: \(String(describing: title)), sfSymbol: \(String(describing: sfSymbol)), badge: \(String(describing: badge)), sidebarOnly: \(String(describing: sidebarOnly)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAction: Hashable, CustomStringConvertible {
  var title: String
  var sfSymbol: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAction? {
    let title = pigeonVar_list[0] as! String
    let sfSymbol = pigeonVar_list[1] as! String

    return NativeAction(
      title: title,
      sfSymbol: sfSymbol
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      sfSymbol,
    ]
  }
  static func == (lhs: NativeAction, rhs: NativeAction) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAction")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
  }

  public var description: String {
    return "NativeAction(title: \(String(describing: title)), sfSymbol: \(String(describing: sfSymbol)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeFooter: Hashable, CustomStringConvertible {
  var title: String
  var subtitle: String
  var sfSymbol: String
  var semanticLabel: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeFooter? {
    let title = pigeonVar_list[0] as! String
    let subtitle = pigeonVar_list[1] as! String
    let sfSymbol = pigeonVar_list[2] as! String
    let semanticLabel = pigeonVar_list[3] as! String

    return NativeFooter(
      title: title,
      subtitle: subtitle,
      sfSymbol: sfSymbol,
      semanticLabel: semanticLabel
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      subtitle,
      sfSymbol,
      semanticLabel,
    ]
  }
  static func == (lhs: NativeFooter, rhs: NativeFooter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.subtitle, rhs.subtitle) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol) && NativeShellApiPigeonInternal.deepEquals(lhs.semanticLabel, rhs.semanticLabel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeFooter")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: subtitle, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: semanticLabel, hasher: &hasher)
  }

  public var description: String {
    return "NativeFooter(title: \(String(describing: title)), subtitle: \(String(describing: subtitle)), sfSymbol: \(String(describing: sfSymbol)), semanticLabel: \(String(describing: semanticLabel)))"
  }
}

/// The whole chrome. Applied in order: tabs, selection, footer, tint,
/// appearance, direction, visibility.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeChromeConfig: Hashable, CustomStringConvertible {
  var engaged: Bool
  var tabs: [NativeTab]
  var selectedIndex: Int64
  var trailing: NativeAction? = nil
  var footer: NativeFooter? = nil
  var tintArgb: Int64
  var dark: Bool
  var rtl: Bool
  var hidden: Bool
  var interactive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeChromeConfig? {
    let engaged = pigeonVar_list[0] as! Bool
    let tabs = pigeonVar_list[1] as! [NativeTab]
    let selectedIndex = pigeonVar_list[2] as! Int64
    let trailing: NativeAction? = nilOrValue(pigeonVar_list[3])
    let footer: NativeFooter? = nilOrValue(pigeonVar_list[4])
    let tintArgb = pigeonVar_list[5] as! Int64
    let dark = pigeonVar_list[6] as! Bool
    let rtl = pigeonVar_list[7] as! Bool
    let hidden = pigeonVar_list[8] as! Bool
    let interactive = pigeonVar_list[9] as! Bool

    return NativeChromeConfig(
      engaged: engaged,
      tabs: tabs,
      selectedIndex: selectedIndex,
      trailing: trailing,
      footer: footer,
      tintArgb: tintArgb,
      dark: dark,
      rtl: rtl,
      hidden: hidden,
      interactive: interactive
    )
  }
  func toList() -> [Any?] {
    return [
      engaged,
      tabs,
      selectedIndex,
      trailing,
      footer,
      tintArgb,
      dark,
      rtl,
      hidden,
      interactive,
    ]
  }
  static func == (lhs: NativeChromeConfig, rhs: NativeChromeConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.engaged, rhs.engaged) && NativeShellApiPigeonInternal.deepEquals(lhs.tabs, rhs.tabs) && NativeShellApiPigeonInternal.deepEquals(lhs.selectedIndex, rhs.selectedIndex) && NativeShellApiPigeonInternal.deepEquals(lhs.trailing, rhs.trailing) && NativeShellApiPigeonInternal.deepEquals(lhs.footer, rhs.footer) && NativeShellApiPigeonInternal.deepEquals(lhs.tintArgb, rhs.tintArgb) && NativeShellApiPigeonInternal.deepEquals(lhs.dark, rhs.dark) && NativeShellApiPigeonInternal.deepEquals(lhs.rtl, rhs.rtl) && NativeShellApiPigeonInternal.deepEquals(lhs.hidden, rhs.hidden) && NativeShellApiPigeonInternal.deepEquals(lhs.interactive, rhs.interactive)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeChromeConfig")
    NativeShellApiPigeonInternal.deepHash(value: engaged, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: tabs, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: selectedIndex, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: trailing, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: footer, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: tintArgb, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: dark, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: rtl, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: hidden, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: interactive, hasher: &hasher)
  }

  public var description: String {
    return "NativeChromeConfig(engaged: \(String(describing: engaged)), tabs: \(String(describing: tabs)), selectedIndex: \(String(describing: selectedIndex)), trailing: \(String(describing: trailing)), footer: \(String(describing: footer)), tintArgb: \(String(describing: tintArgb)), dark: \(String(describing: dark)), rtl: \(String(describing: rtl)), hidden: \(String(describing: hidden)), interactive: \(String(describing: interactive)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeWindowControls: Hashable, CustomStringConvertible {
  var leading: Double
  var top: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeWindowControls? {
    let leading = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double

    return NativeWindowControls(
      leading: leading,
      top: top
    )
  }
  func toList() -> [Any?] {
    return [
      leading,
      top,
    ]
  }
  static func == (lhs: NativeWindowControls, rhs: NativeWindowControls) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.leading, rhs.leading) && NativeShellApiPigeonInternal.deepEquals(lhs.top, rhs.top)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeWindowControls")
    NativeShellApiPigeonInternal.deepHash(value: leading, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: top, hasher: &hasher)
  }

  public var description: String {
    return "NativeWindowControls(leading: \(String(describing: leading)), top: \(String(describing: top)))"
  }
}

private class NativeShellApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeSidebar(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeUnavailableReason(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeTapTarget(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return NativeShellState.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeTab.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeAction.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeFooter.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeChromeConfig.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeWindowControls.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeShellApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeSidebar {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeUnavailableReason {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeTapTarget {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeShellState {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeTab {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAction {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeFooter {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeChromeConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeWindowControls {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeShellApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeShellApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeShellApiPigeonCodecWriter(data: data)
  }
}

class NativeShellApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeShellApiPigeonCodec(readerWriter: NativeShellApiPigeonCodecReaderWriter())
}

/// Dart → native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeShellHostApi {
  func attach() throws -> NativeShellState
  func update(config: NativeChromeConfig) throws
  func setSidebarVisible(visible: Bool) throws
  func windowControls() throws -> NativeWindowControls
  /// Debug builds only: runs the same code path as a user tap on [target].
  /// Release builds ignore it.
  func debugTap(target: NativeTapTarget, index: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeShellHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeShellApiPigeonCodec.shared }
  /// Sets up an instance of `NativeShellHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeShellHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let attachChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.attach\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attachChannel.setMessageHandler { _, reply in
        do {
          let result = try api.attach()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      attachChannel.setMessageHandler(nil)
    }
    let updateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! NativeChromeConfig
        do {
          try api.update(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
    let setSidebarVisibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSidebarVisible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSidebarVisibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let visibleArg = args[0] as! Bool
        do {
          try api.setSidebarVisible(visible: visibleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSidebarVisibleChannel.setMessageHandler(nil)
    }
    let windowControlsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.windowControls\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      windowControlsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.windowControls()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      windowControlsChannel.setMessageHandler(nil)
    }
    /// Debug builds only: runs the same code path as a user tap on [target].
    /// Release builds ignore it.
    let debugTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.debugTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let targetArg = args[0] as! NativeTapTarget
        let indexArg = args[1] as! Int64
        do {
          try api.debugTap(target: targetArg, index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugTapChannel.setMessageHandler(nil)
    }
  }
}

/// Native → Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeShellFlutterApiProtocol {
  func onDestinationTapped(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTrailingTapped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFooterTapped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStateChanged(state stateArg: NativeShellState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWindowControlsChanged(controls controlsArg: NativeWindowControls, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NativeShellFlutterApi: NativeShellFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeShellApiPigeonCodec {
    return NativeShellApiPigeonCodec.shared
  }
  func onDestinationTapped(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onDestinationTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onTrailingTapped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onTrailingTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onFooterTapped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onFooterTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateChanged(state stateArg: NativeShellState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWindowControlsChanged(controls controlsArg: NativeWindowControls, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onWindowControlsChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([controlsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
