// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum NativeShellApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Where the native sidebar is.
enum NativeSidebar: Int, CaseIterable {
  case hidden = 0
  case overlay = 1
  case tiled = 2
}

/// Why the native shell is not installed.
enum NativeUnavailableReason: Int, CaseIterable {
  case osTooOld = 0
  case iPadAppOnMac = 1
  case notEnabled = 2
  case disabledByEnvironment = 3
  case rootNotFlutter = 4
  case registeredLate = 5
}

/// Test-only: what `debugTap` taps.
enum NativeTapTarget: Int, CaseIterable {
  case destination = 0
  case trailing = 1
  case footer = 2
  case searchField = 3
  case searchCancel = 4
  case back = 5
}

/// What a native dialog is.
enum NativeDialogKind: Int, CaseIterable {
  case alert = 0
  case actionSheet = 1
}

/// How an action looks (`UIAlertAction.Style`).
enum NativeDialogActionStyle: Int, CaseIterable {
  case standard = 0
  case cancel = 1
  case destructive = 2
}

/// How a dialog ended.
enum NativeDialogOutcome: Int, CaseIterable {
  case chose = 0
  case dismissed = 1
  case unavailable = 2
}

/// Why a dialog was not shown (spec P3a §5.2).
enum NativeDialogUnavailableReason: Int, CaseIterable {
  case osTooOld = 0
  case noWindow = 1
  case refused = 2
  case disabledByEnvironment = 3
}

/// What `attach()` returns and `onStateChanged` pushes.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeShellState: Hashable, CustomStringConvertible {
  var installed: Bool
  var compact: Bool
  var sidebar: NativeSidebar
  var unavailableReason: NativeUnavailableReason? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeShellState? {
    let installed = pigeonVar_list[0] as! Bool
    let compact = pigeonVar_list[1] as! Bool
    let sidebar = pigeonVar_list[2] as! NativeSidebar
    let unavailableReason: NativeUnavailableReason? = nilOrValue(pigeonVar_list[3])

    return NativeShellState(
      installed: installed,
      compact: compact,
      sidebar: sidebar,
      unavailableReason: unavailableReason
    )
  }
  func toList() -> [Any?] {
    return [
      installed,
      compact,
      sidebar,
      unavailableReason,
    ]
  }
  static func == (lhs: NativeShellState, rhs: NativeShellState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.installed, rhs.installed) && NativeShellApiPigeonInternal.deepEquals(lhs.compact, rhs.compact) && NativeShellApiPigeonInternal.deepEquals(lhs.sidebar, rhs.sidebar) && NativeShellApiPigeonInternal.deepEquals(lhs.unavailableReason, rhs.unavailableReason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeShellState")
    NativeShellApiPigeonInternal.deepHash(value: installed, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: compact, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sidebar, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: unavailableReason, hasher: &hasher)
  }

  public var description: String {
    return "NativeShellState(installed: \(String(describing: installed)), compact: \(String(describing: compact)), sidebar: \(String(describing: sidebar)), unavailableReason: \(String(describing: unavailableReason)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeTab: Hashable, CustomStringConvertible {
  var title: String
  var sfSymbol: String
  var badge: String? = nil
  var sidebarOnly: Bool
  var search: Bool
  var pages: [NativePage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTab? {
    let title = pigeonVar_list[0] as! String
    let sfSymbol = pigeonVar_list[1] as! String
    let badge: String? = nilOrValue(pigeonVar_list[2])
    let sidebarOnly = pigeonVar_list[3] as! Bool
    let search = pigeonVar_list[4] as! Bool
    let pages = pigeonVar_list[5] as! [NativePage]

    return NativeTab(
      title: title,
      sfSymbol: sfSymbol,
      badge: badge,
      sidebarOnly: sidebarOnly,
      search: search,
      pages: pages
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      sfSymbol,
      badge,
      sidebarOnly,
      search,
      pages,
    ]
  }
  static func == (lhs: NativeTab, rhs: NativeTab) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol) && NativeShellApiPigeonInternal.deepEquals(lhs.badge, rhs.badge) && NativeShellApiPigeonInternal.deepEquals(lhs.sidebarOnly, rhs.sidebarOnly) && NativeShellApiPigeonInternal.deepEquals(lhs.search, rhs.search) && NativeShellApiPigeonInternal.deepEquals(lhs.pages, rhs.pages)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeTab")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: badge, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sidebarOnly, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: search, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: pages, hasher: &hasher)
  }

  public var description: String {
    return "NativeTab(title: \(String(describing: title)), sfSymbol: \(String(describing: sfSymbol)), badge: \(String(describing: badge)), sidebarOnly: \(String(describing: sidebarOnly)), search: \(String(describing: search)), pages: \(String(describing: pages)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAction: Hashable, CustomStringConvertible {
  var title: String
  var sfSymbol: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAction? {
    let title = pigeonVar_list[0] as! String
    let sfSymbol = pigeonVar_list[1] as! String

    return NativeAction(
      title: title,
      sfSymbol: sfSymbol
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      sfSymbol,
    ]
  }
  static func == (lhs: NativeAction, rhs: NativeAction) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAction")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
  }

  public var description: String {
    return "NativeAction(title: \(String(describing: title)), sfSymbol: \(String(describing: sfSymbol)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeFooter: Hashable, CustomStringConvertible {
  var title: String
  var subtitle: String
  var sfSymbol: String
  var semanticLabel: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeFooter? {
    let title = pigeonVar_list[0] as! String
    let subtitle = pigeonVar_list[1] as! String
    let sfSymbol = pigeonVar_list[2] as! String
    let semanticLabel = pigeonVar_list[3] as! String

    return NativeFooter(
      title: title,
      subtitle: subtitle,
      sfSymbol: sfSymbol,
      semanticLabel: semanticLabel
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      subtitle,
      sfSymbol,
      semanticLabel,
    ]
  }
  static func == (lhs: NativeFooter, rhs: NativeFooter) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.subtitle, rhs.subtitle) && NativeShellApiPigeonInternal.deepEquals(lhs.sfSymbol, rhs.sfSymbol) && NativeShellApiPigeonInternal.deepEquals(lhs.semanticLabel, rhs.semanticLabel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeFooter")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: subtitle, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sfSymbol, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: semanticLabel, hasher: &hasher)
  }

  public var description: String {
    return "NativeFooter(title: \(String(describing: title)), subtitle: \(String(describing: subtitle)), sfSymbol: \(String(describing: sfSymbol)), semanticLabel: \(String(describing: semanticLabel)))"
  }
}

/// One page of a tab's navigation stack (root first).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativePage: Hashable, CustomStringConvertible {
  var title: String
  var largeTitle: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePage? {
    let title = pigeonVar_list[0] as! String
    let largeTitle: Bool? = nilOrValue(pigeonVar_list[1])

    return NativePage(
      title: title,
      largeTitle: largeTitle
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      largeTitle,
    ]
  }
  static func == (lhs: NativePage, rhs: NativePage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.largeTitle, rhs.largeTitle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePage")
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: largeTitle, hasher: &hasher)
  }

  public var description: String {
    return "NativePage(title: \(String(describing: title)), largeTitle: \(String(describing: largeTitle)))"
  }
}

/// The search tab's field.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeSearchConfig: Hashable, CustomStringConvertible {
  var placeholder: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeSearchConfig? {
    let placeholder: String? = nilOrValue(pigeonVar_list[0])

    return NativeSearchConfig(
      placeholder: placeholder
    )
  }
  func toList() -> [Any?] {
    return [
      placeholder
    ]
  }
  static func == (lhs: NativeSearchConfig, rhs: NativeSearchConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.placeholder, rhs.placeholder)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeSearchConfig")
    NativeShellApiPigeonInternal.deepHash(value: placeholder, hasher: &hasher)
  }

  public var description: String {
    return "NativeSearchConfig(placeholder: \(String(describing: placeholder)))"
  }
}

/// A rectangle in the Flutter view's coordinates (points).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeRect: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return NativeRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: NativeRect, rhs: NativeRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.x, rhs.x) && NativeShellApiPigeonInternal.deepEquals(lhs.y, rhs.y) && NativeShellApiPigeonInternal.deepEquals(lhs.width, rhs.width) && NativeShellApiPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRect")
    NativeShellApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "NativeRect(x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Debug builds: the native search and page state, for integration tests.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeDebugSnapshot: Hashable, CustomStringConvertible {
  /// The selected `UITab`'s identifier ("destination<i>", or "" when none).
  var selectedTab: String
  var searchActive: Bool
  var searchText: String
  /// The realised `searchBarPlacement`: "integrated", "stacked", … or "".
  var placement: String
  /// The search tab's navigation titles, root first.
  var pageTitles: [String]
  var fieldFrame: NativeRect
  var firstResponderIsSearch: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDebugSnapshot? {
    let selectedTab = pigeonVar_list[0] as! String
    let searchActive = pigeonVar_list[1] as! Bool
    let searchText = pigeonVar_list[2] as! String
    let placement = pigeonVar_list[3] as! String
    let pageTitles = pigeonVar_list[4] as! [String]
    let fieldFrame = pigeonVar_list[5] as! NativeRect
    let firstResponderIsSearch = pigeonVar_list[6] as! Bool

    return NativeDebugSnapshot(
      selectedTab: selectedTab,
      searchActive: searchActive,
      searchText: searchText,
      placement: placement,
      pageTitles: pageTitles,
      fieldFrame: fieldFrame,
      firstResponderIsSearch: firstResponderIsSearch
    )
  }
  func toList() -> [Any?] {
    return [
      selectedTab,
      searchActive,
      searchText,
      placement,
      pageTitles,
      fieldFrame,
      firstResponderIsSearch,
    ]
  }
  static func == (lhs: NativeDebugSnapshot, rhs: NativeDebugSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.selectedTab, rhs.selectedTab) && NativeShellApiPigeonInternal.deepEquals(lhs.searchActive, rhs.searchActive) && NativeShellApiPigeonInternal.deepEquals(lhs.searchText, rhs.searchText) && NativeShellApiPigeonInternal.deepEquals(lhs.placement, rhs.placement) && NativeShellApiPigeonInternal.deepEquals(lhs.pageTitles, rhs.pageTitles) && NativeShellApiPigeonInternal.deepEquals(lhs.fieldFrame, rhs.fieldFrame) && NativeShellApiPigeonInternal.deepEquals(lhs.firstResponderIsSearch, rhs.firstResponderIsSearch)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDebugSnapshot")
    NativeShellApiPigeonInternal.deepHash(value: selectedTab, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: searchActive, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: searchText, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: placement, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: pageTitles, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: fieldFrame, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: firstResponderIsSearch, hasher: &hasher)
  }

  public var description: String {
    return "NativeDebugSnapshot(selectedTab: \(String(describing: selectedTab)), searchActive: \(String(describing: searchActive)), searchText: \(String(describing: searchText)), placement: \(String(describing: placement)), pageTitles: \(String(describing: pageTitles)), fieldFrame: \(String(describing: fieldFrame)), firstResponderIsSearch: \(String(describing: firstResponderIsSearch)))"
  }
}

/// The whole chrome. Applied in order: tabs, selection, footer, tint,
/// appearance, direction, visibility.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeChromeConfig: Hashable, CustomStringConvertible {
  var engaged: Bool
  var tabs: [NativeTab]
  var selectedIndex: Int64
  var trailing: NativeAction? = nil
  var footer: NativeFooter? = nil
  var search: NativeSearchConfig? = nil
  var tintArgb: Int64
  var dark: Bool
  var rtl: Bool
  var hidden: Bool
  var interactive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeChromeConfig? {
    let engaged = pigeonVar_list[0] as! Bool
    let tabs = pigeonVar_list[1] as! [NativeTab]
    let selectedIndex = pigeonVar_list[2] as! Int64
    let trailing: NativeAction? = nilOrValue(pigeonVar_list[3])
    let footer: NativeFooter? = nilOrValue(pigeonVar_list[4])
    let search: NativeSearchConfig? = nilOrValue(pigeonVar_list[5])
    let tintArgb = pigeonVar_list[6] as! Int64
    let dark = pigeonVar_list[7] as! Bool
    let rtl = pigeonVar_list[8] as! Bool
    let hidden = pigeonVar_list[9] as! Bool
    let interactive = pigeonVar_list[10] as! Bool

    return NativeChromeConfig(
      engaged: engaged,
      tabs: tabs,
      selectedIndex: selectedIndex,
      trailing: trailing,
      footer: footer,
      search: search,
      tintArgb: tintArgb,
      dark: dark,
      rtl: rtl,
      hidden: hidden,
      interactive: interactive
    )
  }
  func toList() -> [Any?] {
    return [
      engaged,
      tabs,
      selectedIndex,
      trailing,
      footer,
      search,
      tintArgb,
      dark,
      rtl,
      hidden,
      interactive,
    ]
  }
  static func == (lhs: NativeChromeConfig, rhs: NativeChromeConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.engaged, rhs.engaged) && NativeShellApiPigeonInternal.deepEquals(lhs.tabs, rhs.tabs) && NativeShellApiPigeonInternal.deepEquals(lhs.selectedIndex, rhs.selectedIndex) && NativeShellApiPigeonInternal.deepEquals(lhs.trailing, rhs.trailing) && NativeShellApiPigeonInternal.deepEquals(lhs.footer, rhs.footer) && NativeShellApiPigeonInternal.deepEquals(lhs.search, rhs.search) && NativeShellApiPigeonInternal.deepEquals(lhs.tintArgb, rhs.tintArgb) && NativeShellApiPigeonInternal.deepEquals(lhs.dark, rhs.dark) && NativeShellApiPigeonInternal.deepEquals(lhs.rtl, rhs.rtl) && NativeShellApiPigeonInternal.deepEquals(lhs.hidden, rhs.hidden) && NativeShellApiPigeonInternal.deepEquals(lhs.interactive, rhs.interactive)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeChromeConfig")
    NativeShellApiPigeonInternal.deepHash(value: engaged, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: tabs, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: selectedIndex, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: trailing, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: footer, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: search, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: tintArgb, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: dark, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: rtl, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: hidden, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: interactive, hasher: &hasher)
  }

  public var description: String {
    return "NativeChromeConfig(engaged: \(String(describing: engaged)), tabs: \(String(describing: tabs)), selectedIndex: \(String(describing: selectedIndex)), trailing: \(String(describing: trailing)), footer: \(String(describing: footer)), search: \(String(describing: search)), tintArgb: \(String(describing: tintArgb)), dark: \(String(describing: dark)), rtl: \(String(describing: rtl)), hidden: \(String(describing: hidden)), interactive: \(String(describing: interactive)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeWindowControls: Hashable, CustomStringConvertible {
  var leading: Double
  var top: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeWindowControls? {
    let leading = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double

    return NativeWindowControls(
      leading: leading,
      top: top
    )
  }
  func toList() -> [Any?] {
    return [
      leading,
      top,
    ]
  }
  static func == (lhs: NativeWindowControls, rhs: NativeWindowControls) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.leading, rhs.leading) && NativeShellApiPigeonInternal.deepEquals(lhs.top, rhs.top)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeWindowControls")
    NativeShellApiPigeonInternal.deepHash(value: leading, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: top, hasher: &hasher)
  }

  public var description: String {
    return "NativeWindowControls(leading: \(String(describing: leading)), top: \(String(describing: top)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeDialogAction: Hashable, CustomStringConvertible {
  var label: String
  var style: NativeDialogActionStyle
  var enabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDialogAction? {
    let label = pigeonVar_list[0] as! String
    let style = pigeonVar_list[1] as! NativeDialogActionStyle
    let enabled = pigeonVar_list[2] as! Bool

    return NativeDialogAction(
      label: label,
      style: style,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      style,
      enabled,
    ]
  }
  static func == (lhs: NativeDialogAction, rhs: NativeDialogAction) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.label, rhs.label) && NativeShellApiPigeonInternal.deepEquals(lhs.style, rhs.style) && NativeShellApiPigeonInternal.deepEquals(lhs.enabled, rhs.enabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDialogAction")
    NativeShellApiPigeonInternal.deepHash(value: label, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: style, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: enabled, hasher: &hasher)
  }

  public var description: String {
    return "NativeDialogAction(label: \(String(describing: label)), style: \(String(describing: style)), enabled: \(String(describing: enabled)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeDialogRequest: Hashable, CustomStringConvertible {
  var kind: NativeDialogKind
  var title: String? = nil
  var message: String? = nil
  var actions: [NativeDialogAction]
  var preferredIndex: Int64? = nil
  var anchor: NativeRect? = nil
  var tintArgb: Int64
  var dark: Bool
  var rtl: Bool
  var requireGlass: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDialogRequest? {
    let kind = pigeonVar_list[0] as! NativeDialogKind
    let title: String? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])
    let actions = pigeonVar_list[3] as! [NativeDialogAction]
    let preferredIndex: Int64? = nilOrValue(pigeonVar_list[4])
    let anchor: NativeRect? = nilOrValue(pigeonVar_list[5])
    let tintArgb = pigeonVar_list[6] as! Int64
    let dark = pigeonVar_list[7] as! Bool
    let rtl = pigeonVar_list[8] as! Bool
    let requireGlass = pigeonVar_list[9] as! Bool

    return NativeDialogRequest(
      kind: kind,
      title: title,
      message: message,
      actions: actions,
      preferredIndex: preferredIndex,
      anchor: anchor,
      tintArgb: tintArgb,
      dark: dark,
      rtl: rtl,
      requireGlass: requireGlass
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      title,
      message,
      actions,
      preferredIndex,
      anchor,
      tintArgb,
      dark,
      rtl,
      requireGlass,
    ]
  }
  static func == (lhs: NativeDialogRequest, rhs: NativeDialogRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.message, rhs.message) && NativeShellApiPigeonInternal.deepEquals(lhs.actions, rhs.actions) && NativeShellApiPigeonInternal.deepEquals(lhs.preferredIndex, rhs.preferredIndex) && NativeShellApiPigeonInternal.deepEquals(lhs.anchor, rhs.anchor) && NativeShellApiPigeonInternal.deepEquals(lhs.tintArgb, rhs.tintArgb) && NativeShellApiPigeonInternal.deepEquals(lhs.dark, rhs.dark) && NativeShellApiPigeonInternal.deepEquals(lhs.rtl, rhs.rtl) && NativeShellApiPigeonInternal.deepEquals(lhs.requireGlass, rhs.requireGlass)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDialogRequest")
    NativeShellApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: actions, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: preferredIndex, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: anchor, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: tintArgb, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: dark, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: rtl, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: requireGlass, hasher: &hasher)
  }

  public var description: String {
    return "NativeDialogRequest(kind: \(String(describing: kind)), title: \(String(describing: title)), message: \(String(describing: message)), actions: \(String(describing: actions)), preferredIndex: \(String(describing: preferredIndex)), anchor: \(String(describing: anchor)), tintArgb: \(String(describing: tintArgb)), dark: \(String(describing: dark)), rtl: \(String(describing: rtl)), requireGlass: \(String(describing: requireGlass)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeDialogResult: Hashable, CustomStringConvertible {
  var outcome: NativeDialogOutcome
  var actionIndex: Int64? = nil
  var reason: NativeDialogUnavailableReason? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDialogResult? {
    let outcome = pigeonVar_list[0] as! NativeDialogOutcome
    let actionIndex: Int64? = nilOrValue(pigeonVar_list[1])
    let reason: NativeDialogUnavailableReason? = nilOrValue(pigeonVar_list[2])

    return NativeDialogResult(
      outcome: outcome,
      actionIndex: actionIndex,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      outcome,
      actionIndex,
      reason,
    ]
  }
  static func == (lhs: NativeDialogResult, rhs: NativeDialogResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && NativeShellApiPigeonInternal.deepEquals(lhs.actionIndex, rhs.actionIndex) && NativeShellApiPigeonInternal.deepEquals(lhs.reason, rhs.reason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDialogResult")
    NativeShellApiPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: actionIndex, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: reason, hasher: &hasher)
  }

  public var description: String {
    return "NativeDialogResult(outcome: \(String(describing: outcome)), actionIndex: \(String(describing: actionIndex)), reason: \(String(describing: reason)))"
  }
}

/// Test-only: the dialog on screen.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeDialogSnapshot: Hashable, CustomStringConvertible {
  var kind: NativeDialogKind
  var title: String? = nil
  var message: String? = nil
  var labels: [String]
  var preferredIndex: Int64? = nil
  var sourceRect: NativeRect? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDialogSnapshot? {
    let kind = pigeonVar_list[0] as! NativeDialogKind
    let title: String? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])
    let labels = pigeonVar_list[3] as! [String]
    let preferredIndex: Int64? = nilOrValue(pigeonVar_list[4])
    let sourceRect: NativeRect? = nilOrValue(pigeonVar_list[5])

    return NativeDialogSnapshot(
      kind: kind,
      title: title,
      message: message,
      labels: labels,
      preferredIndex: preferredIndex,
      sourceRect: sourceRect
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      title,
      message,
      labels,
      preferredIndex,
      sourceRect,
    ]
  }
  static func == (lhs: NativeDialogSnapshot, rhs: NativeDialogSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return NativeShellApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && NativeShellApiPigeonInternal.deepEquals(lhs.title, rhs.title) && NativeShellApiPigeonInternal.deepEquals(lhs.message, rhs.message) && NativeShellApiPigeonInternal.deepEquals(lhs.labels, rhs.labels) && NativeShellApiPigeonInternal.deepEquals(lhs.preferredIndex, rhs.preferredIndex) && NativeShellApiPigeonInternal.deepEquals(lhs.sourceRect, rhs.sourceRect)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDialogSnapshot")
    NativeShellApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: labels, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: preferredIndex, hasher: &hasher)
    NativeShellApiPigeonInternal.deepHash(value: sourceRect, hasher: &hasher)
  }

  public var description: String {
    return "NativeDialogSnapshot(kind: \(String(describing: kind)), title: \(String(describing: title)), message: \(String(describing: message)), labels: \(String(describing: labels)), preferredIndex: \(String(describing: preferredIndex)), sourceRect: \(String(describing: sourceRect)))"
  }
}

private class NativeShellApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeSidebar(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeUnavailableReason(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeTapTarget(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeDialogKind(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeDialogActionStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeDialogOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeDialogUnavailableReason(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return NativeShellState.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeTab.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeAction.fromList(self.readValue() as! [Any?])
    case 139:
      return NativeFooter.fromList(self.readValue() as! [Any?])
    case 140:
      return NativePage.fromList(self.readValue() as! [Any?])
    case 141:
      return NativeSearchConfig.fromList(self.readValue() as! [Any?])
    case 142:
      return NativeRect.fromList(self.readValue() as! [Any?])
    case 143:
      return NativeDebugSnapshot.fromList(self.readValue() as! [Any?])
    case 144:
      return NativeChromeConfig.fromList(self.readValue() as! [Any?])
    case 145:
      return NativeWindowControls.fromList(self.readValue() as! [Any?])
    case 146:
      return NativeDialogAction.fromList(self.readValue() as! [Any?])
    case 147:
      return NativeDialogRequest.fromList(self.readValue() as! [Any?])
    case 148:
      return NativeDialogResult.fromList(self.readValue() as! [Any?])
    case 149:
      return NativeDialogSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeShellApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeSidebar {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeUnavailableReason {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeTapTarget {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeDialogKind {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeDialogActionStyle {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeDialogOutcome {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeDialogUnavailableReason {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeShellState {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeTab {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAction {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? NativeFooter {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? NativePage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? NativeSearchConfig {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRect {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDebugSnapshot {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? NativeChromeConfig {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? NativeWindowControls {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDialogAction {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDialogRequest {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDialogResult {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDialogSnapshot {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeShellApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeShellApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeShellApiPigeonCodecWriter(data: data)
  }
}

class NativeShellApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeShellApiPigeonCodec(readerWriter: NativeShellApiPigeonCodecReaderWriter())
}


/// Dart → native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeShellHostApi {
  func attach() throws -> NativeShellState
  func update(config: NativeChromeConfig) throws
  func setSidebarVisible(visible: Bool) throws
  func windowControls() throws -> NativeWindowControls
  /// Debug builds only: runs the same code path as a user tap on [target].
  /// Release builds ignore it.
  func debugTap(target: NativeTapTarget, index: Int64) throws
  /// Sets the search field's text once no IME composition is in progress.
  func setSearchText(text: String) throws
  /// Presents or dismisses the search; dismissing keeps the text.
  func setSearchActive(active: Bool) throws
  /// The top page's scroll offset of tab [tab] (proxy scroll view).
  func setPageScroll(tab: Int64, offset: Double) throws
  /// Debug builds: the native search and page state. Release: empty.
  func debugSnapshot() throws -> NativeDebugSnapshot
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeShellHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeShellApiPigeonCodec.shared }
  /// Sets up an instance of `NativeShellHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeShellHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let attachChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.attach\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attachChannel.setMessageHandler { _, reply in
        do {
          let result = try api.attach()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      attachChannel.setMessageHandler(nil)
    }
    let updateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! NativeChromeConfig
        do {
          try api.update(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
    let setSidebarVisibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSidebarVisible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSidebarVisibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let visibleArg = args[0] as! Bool
        do {
          try api.setSidebarVisible(visible: visibleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSidebarVisibleChannel.setMessageHandler(nil)
    }
    let windowControlsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.windowControls\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      windowControlsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.windowControls()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      windowControlsChannel.setMessageHandler(nil)
    }
    /// Debug builds only: runs the same code path as a user tap on [target].
    /// Release builds ignore it.
    let debugTapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.debugTap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugTapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let targetArg = args[0] as! NativeTapTarget
        let indexArg = args[1] as! Int64
        do {
          try api.debugTap(target: targetArg, index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugTapChannel.setMessageHandler(nil)
    }
    /// Sets the search field's text once no IME composition is in progress.
    let setSearchTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSearchText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSearchTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          try api.setSearchText(text: textArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSearchTextChannel.setMessageHandler(nil)
    }
    /// Presents or dismisses the search; dismissing keeps the text.
    let setSearchActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSearchActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSearchActiveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let activeArg = args[0] as! Bool
        do {
          try api.setSearchActive(active: activeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSearchActiveChannel.setMessageHandler(nil)
    }
    /// The top page's scroll offset of tab [tab] (proxy scroll view).
    let setPageScrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setPageScroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPageScrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tabArg = args[0] as! Int64
        let offsetArg = args[1] as! Double
        do {
          try api.setPageScroll(tab: tabArg, offset: offsetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPageScrollChannel.setMessageHandler(nil)
    }
    /// Debug builds: the native search and page state. Release: empty.
    let debugSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.debugSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.debugSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugSnapshotChannel.setMessageHandler(nil)
    }
  }
}

/// Native → Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeShellFlutterApiProtocol {
  func onDestinationTapped(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTrailingTapped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFooterTapped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStateChanged(state stateArg: NativeShellState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWindowControlsChanged(controls controlsArg: NativeWindowControls, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSearchTextChanged(text textArg: String, composing composingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSearchActiveChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSearchSubmitted(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSearchFieldChanged(frame frameArg: NativeRect, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBackTapped(tab tabArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// UIKit asked to pop tab [tab] to the page at [index] (the back menu, a
  /// pop-to-root); native did not pop.
  func onPopToPage(tab tabArg: Int64, index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NativeShellFlutterApi: NativeShellFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeShellApiPigeonCodec {
    return NativeShellApiPigeonCodec.shared
  }
  func onDestinationTapped(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onDestinationTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onTrailingTapped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onTrailingTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onFooterTapped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onFooterTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateChanged(state stateArg: NativeShellState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWindowControlsChanged(controls controlsArg: NativeWindowControls, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onWindowControlsChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([controlsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSearchTextChanged(text textArg: String, composing composingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchTextChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg, composingArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSearchActiveChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchActiveChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSearchSubmitted(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchSubmitted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSearchFieldChanged(frame frameArg: NativeRect, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchFieldChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([frameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBackTapped(tab tabArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onBackTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tabArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// UIKit asked to pop tab [tab] to the page at [index] (the back menu, a
  /// pop-to-root); native did not pop.
  func onPopToPage(tab tabArg: Int64, index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onPopToPage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tabArg, indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Dart → native dialogs.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeDialogHostApi {
  /// Presents [request]; answers when it closes, or at once when it
  /// cannot be shown.
  func present(request: NativeDialogRequest, completion: @escaping (Result<NativeDialogResult, Error>) -> Void)
  /// Debug builds only: the dialog this engine shows, or null.
  func debugCurrent() throws -> NativeDialogSnapshot?
  /// Debug builds only: closes the dialog this engine shows as if
  /// [actionIndex] were tapped; -1 dismisses it without a choice.
  func debugRespond(actionIndex: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeDialogHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeShellApiPigeonCodec.shared }
  /// Sets up an instance of `NativeDialogHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeDialogHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Presents [request]; answers when it closes, or at once when it
    /// cannot be shown.
    let presentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.present\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeDialogRequest
        api.present(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentChannel.setMessageHandler(nil)
    }
    /// Debug builds only: the dialog this engine shows, or null.
    let debugCurrentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.debugCurrent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugCurrentChannel.setMessageHandler { _, reply in
        do {
          let result = try api.debugCurrent()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugCurrentChannel.setMessageHandler(nil)
    }
    /// Debug builds only: closes the dialog this engine shows as if
    /// [actionIndex] were tapped; -1 dismisses it without a choice.
    let debugRespondChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.debugRespond\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugRespondChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let actionIndexArg = args[0] as! Int64
        do {
          try api.debugRespond(actionIndex: actionIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      debugRespondChannel.setMessageHandler(nil)
    }
  }
}
