// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Where the native sidebar is.
enum NativeSidebar {
  hidden,
  overlay,
  tiled,
}

/// Why the native shell is not installed.
enum NativeUnavailableReason {
  osTooOld,
  iPadAppOnMac,
  notEnabled,
  disabledByEnvironment,
  rootNotFlutter,
  registeredLate,
}

/// Test-only: what `debugTap` taps.
enum NativeTapTarget {
  destination,
  trailing,
  footer,
  searchField,
  searchCancel,
  back,
}

/// What a native dialog is.
enum NativeDialogKind {
  alert,
  actionSheet,
}

/// How an action looks (`UIAlertAction.Style`).
enum NativeDialogActionStyle {
  standard,
  cancel,
  destructive,
}

/// How a dialog ended.
enum NativeDialogOutcome {
  chose,
  dismissed,
  unavailable,
}

/// Why a dialog was not shown (spec P3a §5.2).
enum NativeDialogUnavailableReason {
  osTooOld,
  noWindow,
  refused,
  disabledByEnvironment,
}

/// What `attach()` returns and `onStateChanged` pushes.
class NativeShellState {
  NativeShellState({
    required this.installed,
    required this.compact,
    required this.sidebar,
    this.unavailableReason,
  });

  bool installed;

  bool compact;

  NativeSidebar sidebar;

  NativeUnavailableReason? unavailableReason;

  List<Object?> _toList() {
    return <Object?>[
      installed,
      compact,
      sidebar,
      unavailableReason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeShellState decode(Object result) {
    result as List<Object?>;
    return NativeShellState(
      installed: result[0]! as bool,
      compact: result[1]! as bool,
      sidebar: result[2]! as NativeSidebar,
      unavailableReason: result[3] as NativeUnavailableReason?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeShellState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(installed, other.installed) &&
        _deepEquals(compact, other.compact) &&
        _deepEquals(sidebar, other.sidebar) &&
        _deepEquals(unavailableReason, other.unavailableReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeShellState(installed: $installed, compact: $compact, sidebar: $sidebar, unavailableReason: $unavailableReason)';
  }
}

class NativeTab {
  NativeTab({
    required this.title,
    required this.sfSymbol,
    this.badge,
    required this.sidebarOnly,
    required this.search,
    required this.pages,
  });

  String title;

  String sfSymbol;

  String? badge;

  bool sidebarOnly;

  bool search;

  List<NativePage> pages;

  List<Object?> _toList() {
    return <Object?>[
      title,
      sfSymbol,
      badge,
      sidebarOnly,
      search,
      pages,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeTab decode(Object result) {
    result as List<Object?>;
    return NativeTab(
      title: result[0]! as String,
      sfSymbol: result[1]! as String,
      badge: result[2] as String?,
      sidebarOnly: result[3]! as bool,
      search: result[4]! as bool,
      pages: (result[5]! as List<Object?>).cast<NativePage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeTab || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(sfSymbol, other.sfSymbol) &&
        _deepEquals(badge, other.badge) &&
        _deepEquals(sidebarOnly, other.sidebarOnly) &&
        _deepEquals(search, other.search) &&
        _deepEquals(pages, other.pages);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeTab(title: $title, sfSymbol: $sfSymbol, badge: $badge, sidebarOnly: $sidebarOnly, search: $search, pages: $pages)';
  }
}

class NativeAction {
  NativeAction({
    required this.title,
    required this.sfSymbol,
  });

  String title;

  String sfSymbol;

  List<Object?> _toList() {
    return <Object?>[
      title,
      sfSymbol,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeAction decode(Object result) {
    result as List<Object?>;
    return NativeAction(
      title: result[0]! as String,
      sfSymbol: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(sfSymbol, other.sfSymbol);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAction(title: $title, sfSymbol: $sfSymbol)';
  }
}

class NativeFooter {
  NativeFooter({
    required this.title,
    required this.subtitle,
    required this.sfSymbol,
    required this.semanticLabel,
  });

  String title;

  String subtitle;

  String sfSymbol;

  String semanticLabel;

  List<Object?> _toList() {
    return <Object?>[
      title,
      subtitle,
      sfSymbol,
      semanticLabel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeFooter decode(Object result) {
    result as List<Object?>;
    return NativeFooter(
      title: result[0]! as String,
      subtitle: result[1]! as String,
      sfSymbol: result[2]! as String,
      semanticLabel: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeFooter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(sfSymbol, other.sfSymbol) &&
        _deepEquals(semanticLabel, other.semanticLabel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeFooter(title: $title, subtitle: $subtitle, sfSymbol: $sfSymbol, semanticLabel: $semanticLabel)';
  }
}

/// One page of a tab's navigation stack (root first).
class NativePage {
  NativePage({
    required this.title,
    this.largeTitle,
  });

  String title;

  bool? largeTitle;

  List<Object?> _toList() {
    return <Object?>[
      title,
      largeTitle,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativePage decode(Object result) {
    result as List<Object?>;
    return NativePage(
      title: result[0]! as String,
      largeTitle: result[1] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(largeTitle, other.largeTitle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePage(title: $title, largeTitle: $largeTitle)';
  }
}

/// The search tab's field.
class NativeSearchConfig {
  NativeSearchConfig({
    this.placeholder,
  });

  String? placeholder;

  List<Object?> _toList() {
    return <Object?>[
      placeholder,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeSearchConfig decode(Object result) {
    result as List<Object?>;
    return NativeSearchConfig(
      placeholder: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeSearchConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(placeholder, other.placeholder);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeSearchConfig(placeholder: $placeholder)';
  }
}

/// A rectangle in the Flutter view's coordinates (points).
class NativeRect {
  NativeRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeRect decode(Object result) {
    result as List<Object?>;
    return NativeRect(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRect(x: $x, y: $y, width: $width, height: $height)';
  }
}

/// Debug builds: the native search and page state, for integration tests.
class NativeDebugSnapshot {
  NativeDebugSnapshot({
    required this.selectedTab,
    required this.searchActive,
    required this.searchText,
    required this.placement,
    required this.pageTitles,
    required this.fieldFrame,
    required this.firstResponderIsSearch,
  });

  /// The selected `UITab`'s identifier ("destination<i>", or "" when none).
  String selectedTab;

  bool searchActive;

  String searchText;

  /// The realised `searchBarPlacement`: "integrated", "stacked", … or "".
  String placement;

  /// The search tab's navigation titles, root first.
  List<String> pageTitles;

  NativeRect fieldFrame;

  bool firstResponderIsSearch;

  List<Object?> _toList() {
    return <Object?>[
      selectedTab,
      searchActive,
      searchText,
      placement,
      pageTitles,
      fieldFrame,
      firstResponderIsSearch,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDebugSnapshot decode(Object result) {
    result as List<Object?>;
    return NativeDebugSnapshot(
      selectedTab: result[0]! as String,
      searchActive: result[1]! as bool,
      searchText: result[2]! as String,
      placement: result[3]! as String,
      pageTitles: (result[4]! as List<Object?>).cast<String>(),
      fieldFrame: result[5]! as NativeRect,
      firstResponderIsSearch: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDebugSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(selectedTab, other.selectedTab) &&
        _deepEquals(searchActive, other.searchActive) &&
        _deepEquals(searchText, other.searchText) &&
        _deepEquals(placement, other.placement) &&
        _deepEquals(pageTitles, other.pageTitles) &&
        _deepEquals(fieldFrame, other.fieldFrame) &&
        _deepEquals(firstResponderIsSearch, other.firstResponderIsSearch);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDebugSnapshot(selectedTab: $selectedTab, searchActive: $searchActive, searchText: $searchText, placement: $placement, pageTitles: $pageTitles, fieldFrame: $fieldFrame, firstResponderIsSearch: $firstResponderIsSearch)';
  }
}

/// The whole chrome. Applied in order: tabs, selection, footer, tint,
/// appearance, direction, visibility.
class NativeChromeConfig {
  NativeChromeConfig({
    required this.engaged,
    required this.tabs,
    required this.selectedIndex,
    this.trailing,
    this.footer,
    this.search,
    required this.tintArgb,
    required this.dark,
    required this.rtl,
    required this.hidden,
    required this.interactive,
  });

  bool engaged;

  List<NativeTab> tabs;

  int selectedIndex;

  NativeAction? trailing;

  NativeFooter? footer;

  NativeSearchConfig? search;

  int tintArgb;

  bool dark;

  bool rtl;

  bool hidden;

  bool interactive;

  List<Object?> _toList() {
    return <Object?>[
      engaged,
      tabs,
      selectedIndex,
      trailing,
      footer,
      search,
      tintArgb,
      dark,
      rtl,
      hidden,
      interactive,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeChromeConfig decode(Object result) {
    result as List<Object?>;
    return NativeChromeConfig(
      engaged: result[0]! as bool,
      tabs: (result[1]! as List<Object?>).cast<NativeTab>(),
      selectedIndex: result[2]! as int,
      trailing: result[3] as NativeAction?,
      footer: result[4] as NativeFooter?,
      search: result[5] as NativeSearchConfig?,
      tintArgb: result[6]! as int,
      dark: result[7]! as bool,
      rtl: result[8]! as bool,
      hidden: result[9]! as bool,
      interactive: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeChromeConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(engaged, other.engaged) &&
        _deepEquals(tabs, other.tabs) &&
        _deepEquals(selectedIndex, other.selectedIndex) &&
        _deepEquals(trailing, other.trailing) &&
        _deepEquals(footer, other.footer) &&
        _deepEquals(search, other.search) &&
        _deepEquals(tintArgb, other.tintArgb) &&
        _deepEquals(dark, other.dark) &&
        _deepEquals(rtl, other.rtl) &&
        _deepEquals(hidden, other.hidden) &&
        _deepEquals(interactive, other.interactive);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeChromeConfig(engaged: $engaged, tabs: $tabs, selectedIndex: $selectedIndex, trailing: $trailing, footer: $footer, search: $search, tintArgb: $tintArgb, dark: $dark, rtl: $rtl, hidden: $hidden, interactive: $interactive)';
  }
}

class NativeWindowControls {
  NativeWindowControls({
    required this.leading,
    required this.top,
  });

  double leading;

  double top;

  List<Object?> _toList() {
    return <Object?>[
      leading,
      top,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeWindowControls decode(Object result) {
    result as List<Object?>;
    return NativeWindowControls(
      leading: result[0]! as double,
      top: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeWindowControls || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(leading, other.leading) && _deepEquals(top, other.top);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeWindowControls(leading: $leading, top: $top)';
  }
}

class NativeDialogAction {
  NativeDialogAction({
    required this.label,
    required this.style,
    required this.enabled,
  });

  String label;

  NativeDialogActionStyle style;

  bool enabled;

  List<Object?> _toList() {
    return <Object?>[
      label,
      style,
      enabled,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDialogAction decode(Object result) {
    result as List<Object?>;
    return NativeDialogAction(
      label: result[0]! as String,
      style: result[1]! as NativeDialogActionStyle,
      enabled: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDialogAction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(label, other.label) &&
        _deepEquals(style, other.style) &&
        _deepEquals(enabled, other.enabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDialogAction(label: $label, style: $style, enabled: $enabled)';
  }
}

class NativeDialogRequest {
  NativeDialogRequest({
    required this.kind,
    this.title,
    this.message,
    required this.actions,
    this.preferredIndex,
    this.anchor,
    required this.tintArgb,
    required this.dark,
    required this.rtl,
    required this.requireGlass,
  });

  NativeDialogKind kind;

  String? title;

  String? message;

  List<NativeDialogAction> actions;

  int? preferredIndex;

  NativeRect? anchor;

  int tintArgb;

  bool dark;

  bool rtl;

  bool requireGlass;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      title,
      message,
      actions,
      preferredIndex,
      anchor,
      tintArgb,
      dark,
      rtl,
      requireGlass,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDialogRequest decode(Object result) {
    result as List<Object?>;
    return NativeDialogRequest(
      kind: result[0]! as NativeDialogKind,
      title: result[1] as String?,
      message: result[2] as String?,
      actions: (result[3]! as List<Object?>).cast<NativeDialogAction>(),
      preferredIndex: result[4] as int?,
      anchor: result[5] as NativeRect?,
      tintArgb: result[6]! as int,
      dark: result[7]! as bool,
      rtl: result[8]! as bool,
      requireGlass: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDialogRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(title, other.title) &&
        _deepEquals(message, other.message) &&
        _deepEquals(actions, other.actions) &&
        _deepEquals(preferredIndex, other.preferredIndex) &&
        _deepEquals(anchor, other.anchor) &&
        _deepEquals(tintArgb, other.tintArgb) &&
        _deepEquals(dark, other.dark) &&
        _deepEquals(rtl, other.rtl) &&
        _deepEquals(requireGlass, other.requireGlass);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDialogRequest(kind: $kind, title: $title, message: $message, actions: $actions, preferredIndex: $preferredIndex, anchor: $anchor, tintArgb: $tintArgb, dark: $dark, rtl: $rtl, requireGlass: $requireGlass)';
  }
}

class NativeDialogResult {
  NativeDialogResult({
    required this.outcome,
    this.actionIndex,
    this.reason,
  });

  NativeDialogOutcome outcome;

  int? actionIndex;

  NativeDialogUnavailableReason? reason;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      actionIndex,
      reason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDialogResult decode(Object result) {
    result as List<Object?>;
    return NativeDialogResult(
      outcome: result[0]! as NativeDialogOutcome,
      actionIndex: result[1] as int?,
      reason: result[2] as NativeDialogUnavailableReason?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDialogResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) &&
        _deepEquals(actionIndex, other.actionIndex) &&
        _deepEquals(reason, other.reason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDialogResult(outcome: $outcome, actionIndex: $actionIndex, reason: $reason)';
  }
}

/// Test-only: the dialog on screen.
class NativeDialogSnapshot {
  NativeDialogSnapshot({
    required this.kind,
    this.title,
    this.message,
    required this.labels,
    this.preferredIndex,
    this.sourceRect,
  });

  NativeDialogKind kind;

  String? title;

  String? message;

  List<String> labels;

  int? preferredIndex;

  NativeRect? sourceRect;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      title,
      message,
      labels,
      preferredIndex,
      sourceRect,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDialogSnapshot decode(Object result) {
    result as List<Object?>;
    return NativeDialogSnapshot(
      kind: result[0]! as NativeDialogKind,
      title: result[1] as String?,
      message: result[2] as String?,
      labels: (result[3]! as List<Object?>).cast<String>(),
      preferredIndex: result[4] as int?,
      sourceRect: result[5] as NativeRect?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDialogSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(title, other.title) &&
        _deepEquals(message, other.message) &&
        _deepEquals(labels, other.labels) &&
        _deepEquals(preferredIndex, other.preferredIndex) &&
        _deepEquals(sourceRect, other.sourceRect);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDialogSnapshot(kind: $kind, title: $title, message: $message, labels: $labels, preferredIndex: $preferredIndex, sourceRect: $sourceRect)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeSidebar) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NativeUnavailableReason) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativeTapTarget) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is NativeDialogKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is NativeDialogActionStyle) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is NativeDialogOutcome) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is NativeDialogUnavailableReason) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is NativeShellState) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NativeTab) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is NativeAction) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is NativeFooter) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is NativePage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is NativeSearchConfig) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is NativeRect) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is NativeDebugSnapshot) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is NativeChromeConfig) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is NativeWindowControls) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is NativeDialogAction) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is NativeDialogRequest) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is NativeDialogResult) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is NativeDialogSnapshot) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeSidebar.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeUnavailableReason.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeTapTarget.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeDialogKind.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeDialogActionStyle.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeDialogOutcome.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : NativeDialogUnavailableReason.values[value];
      case 136:
        return NativeShellState.decode(readValue(buffer)!);
      case 137:
        return NativeTab.decode(readValue(buffer)!);
      case 138:
        return NativeAction.decode(readValue(buffer)!);
      case 139:
        return NativeFooter.decode(readValue(buffer)!);
      case 140:
        return NativePage.decode(readValue(buffer)!);
      case 141:
        return NativeSearchConfig.decode(readValue(buffer)!);
      case 142:
        return NativeRect.decode(readValue(buffer)!);
      case 143:
        return NativeDebugSnapshot.decode(readValue(buffer)!);
      case 144:
        return NativeChromeConfig.decode(readValue(buffer)!);
      case 145:
        return NativeWindowControls.decode(readValue(buffer)!);
      case 146:
        return NativeDialogAction.decode(readValue(buffer)!);
      case 147:
        return NativeDialogRequest.decode(readValue(buffer)!);
      case 148:
        return NativeDialogResult.decode(readValue(buffer)!);
      case 149:
        return NativeDialogSnapshot.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart → native.
class NativeShellHostApi {
  /// Constructor for [NativeShellHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeShellHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeShellState> attach() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.attach$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeShellState;
  }

  Future<void> update(NativeChromeConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.update$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setSidebarVisible(bool visible) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSidebarVisible$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[visible],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NativeWindowControls> windowControls() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.windowControls$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeWindowControls;
  }

  /// Debug builds only: runs the same code path as a user tap on [target].
  /// Release builds ignore it.
  Future<void> debugTap(NativeTapTarget target, int index) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.debugTap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[target, index],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Sets the search field's text once no IME composition is in progress.
  Future<void> setSearchText(String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSearchText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Presents or dismisses the search; dismissing keeps the text.
  Future<void> setSearchActive(bool active) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setSearchActive$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[active],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The top page's scroll offset of tab [tab] (proxy scroll view).
  Future<void> setPageScroll(int tab, double offset) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.setPageScroll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[tab, offset],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Debug builds: the native search and page state. Release: empty.
  Future<NativeDebugSnapshot> debugSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellHostApi.debugSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeDebugSnapshot;
  }
}

/// Native → Dart.
abstract class NativeShellFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDestinationTapped(int index);

  void onTrailingTapped();

  void onFooterTapped();

  void onStateChanged(NativeShellState state);

  void onWindowControlsChanged(NativeWindowControls controls);

  void onSearchTextChanged(String text, bool composing);

  void onSearchActiveChanged(bool active);

  void onSearchSubmitted(String text);

  void onSearchFieldChanged(NativeRect frame);

  void onBackTapped(int tab);

  /// UIKit asked to pop tab [tab] to the page at [index] (the back menu, a
  /// pop-to-root); native did not pop.
  void onPopToPage(int tab, int index);

  static void setUp(
    NativeShellFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onDestinationTapped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_index = args[0]! as int;
          try {
            api.onDestinationTapped(arg_index);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onTrailingTapped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onTrailingTapped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onFooterTapped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onFooterTapped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeShellState arg_state = args[0]! as NativeShellState;
          try {
            api.onStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onWindowControlsChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeWindowControls arg_controls =
              args[0]! as NativeWindowControls;
          try {
            api.onWindowControlsChanged(arg_controls);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchTextChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          final bool arg_composing = args[1]! as bool;
          try {
            api.onSearchTextChanged(arg_text, arg_composing);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchActiveChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_active = args[0]! as bool;
          try {
            api.onSearchActiveChanged(arg_active);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchSubmitted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          try {
            api.onSearchSubmitted(arg_text);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onSearchFieldChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeRect arg_frame = args[0]! as NativeRect;
          try {
            api.onSearchFieldChanged(arg_frame);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onBackTapped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_tab = args[0]! as int;
          try {
            api.onBackTapped(arg_tab);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.liquid_shell_ios.NativeShellFlutterApi.onPopToPage$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_tab = args[0]! as int;
          final int arg_index = args[1]! as int;
          try {
            api.onPopToPage(arg_tab, arg_index);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Dart → native dialogs.
class NativeDialogHostApi {
  /// Constructor for [NativeDialogHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeDialogHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Presents [request]; answers when it closes, or at once when it
  /// cannot be shown.
  Future<NativeDialogResult> present(NativeDialogRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.present$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeDialogResult;
  }

  /// Debug builds only: the dialog this engine shows, or null.
  Future<NativeDialogSnapshot?> debugCurrent() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.debugCurrent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as NativeDialogSnapshot?;
  }

  /// Debug builds only: closes the dialog this engine shows as if
  /// [actionIndex] were tapped; -1 dismisses it without a choice.
  Future<void> debugRespond(int actionIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.liquid_shell_ios.NativeDialogHostApi.debugRespond$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[actionIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
